name: 'test hydro'
on: # rebuild any PRs and main branch changes
  push:
  workflow_dispatch:
  
jobs:

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-on-packages/sample-action@2.5.5
        with:
          milliseconds: 1000
